const themes = {
            nature: ["BARK", "BUSH", "CAVE", "DUNE", "FERN", "FOGY", "GALE", "HAIL", "LAKE", "LEAF", "MIST", "MOSS", "NEST", "PEAK", "PINE", "POND", "RAIN", "ROCK", "SAND", "SEED", "SNOW", "SOIL", "STAR", "TIDE", "TREE", "VINE", "WASP", "WIND", "CANY", "GLEN"],
            animals: ["BIRD", "BOAR", "CRAB", "CROW", "DOVE", "DUCK", "FISH", "FLEA", "FROG", "GOAT", "HAWK", "LAMB", "LION", "LYNX", "MICE", "MINK", "MOLE", "MOTH", "PUMA", "SEAL", "SLUG", "SWAN", "TOAD", "WOLF", "WORM", "YAKS", "ZEBU", "OWLS", "BATS", "KITE"],
            food: ["BAKE", "BEAN", "BEEF", "BITE", "BOWL", "CAKE", "CHEW", "CHOW", "COOK", "CORN", "DELI", "DISH", "EATS", "FISH", "FORK", "GRUB", "HERB", "JAMs", "LAMB", "LIME", "MEAL", "MILK", "OVEN", "PEAR", "PORK", "RICE", "SALT", "SOUP", "TUNA", "VEAL"],
            travel: ["BOAT", "CAMP", "CITY", "FARE", "FLEW", "GULF", "HIKE", "JUMP", "LAND", "MILE", "PATH", "PORT", "RAIL", "ROAD", "ROAM", "RUSH", "SHIP", "STAY", "TOUR", "TRAM", "TRIP", "VISA", "WALK", "WAVE", "WING", "YARD", "ZONE", "DOCK", "BUSY", "RAFT"],
            music: ["BAND", "BEAT", "BLOW", "CLAP", "DRUM", "FLUT", "GONG", "HARP", "HORN", "JAZE", "LUTE", "LYRE", "MUTE", "NOTE", "PICK", "PLAY", "RING", "ROCK", "SANG", "SING", "SONG", "TONE", "TUBA", "TUNE", "VIBE", "WAIL", "WHIZ", "YELP", "ZEST", "CHID"],
            sports: ["BOWL", "CLUB", "DART", "DIVE", "GOAL", "GOLF", "HIKE", "JUMP", "KICK", "LIFT", "PACE", "PLAY", "PUCK", "RACE", "RINK", "RUSH", "SHOT", "SINK", "SKIP", "SLAM", "SOAR", "SWIM", "TACK", "TEAM", "TOSS", "WAVE", "WIND", "YARD", "ZONE", "FEND"],
            colors: ["BLUE", "CYAN", "GOLD", "GRAY", "JADE", "LIME", "MINT", "NAVY", "ONYX", "PINK", "PLUM", "ROSE", "RUBY", "SAGE", "SIEN", "SLAT", "SNOW", "TEAL", "WINE", "ZINC", "AQUA", "BRON", "COAL", "DUSK", "FUCH", "HAZY", "INDY", "KHAI", "OLIV", "SEPI"],
            tools: ["AXLE", "BOLT", "CLIP", "DRIL", "FILE", "FUSE", "GEAR", "GRIP", "HOSE", "JACK", "KNOB", "LAMP", "LINK", "LOCK", "NAIL", "PIPE", "PLUG", "PUMP", "RAKE", "ROPE", "SAWY", "SCUD", "SHOV", "TAPE", "TONG", "VISE", "WASH", "WELD", "WREN", "YOKE"],
            space: ["DUST", "FLARE", "GLOW", "HALO", "LUNA", "MARS", "MOON", "NEBU", "NOVA", "ORBIT", "PULS", "RING", "ROCK", "STAR", "SUNY", "TIDE", "VOID", "WARP", "ZETA", "AERO", "BLAZ", "COSM", "DARK", "EONS", "GALX", "IONS", "JETS", "LITE", "MIST", "VEGA"],
            jobs: ["BAKE", "CHEF", "COPY", "DESK", "DIVE", "DOCT", "FARM", "GUID", "HUNT", "JUDG", "MAID", "MINE", "NURSE", "PAIN", "PILOT", "POET", "RANG", "SHOP", "SPY", "TAIL", "TEACH", "VETS", "WAGE", "WELD", "WORK", "ACTS", "BANK", "CASH", "EDIT", "GURU"]
        };